apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodePort.name }}
  namespace: ci-cd
spec:
  type: {{ .Values.nodePort.type }}
  ports:
    - port: 8080
      targetPort: http
      nodePort: 32000
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}