apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.alertManager.cmname" . }}
  namespace: {{ .Values.namespace }}
data:
  {{ .Values.alertManager.configurations.mainConfig.file_name }}: |-
    {{- tpl .Values.alertManager.configurations.mainConfig.data . | nindent 4 }}
  
