apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.alertManager.cmname" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.alertManager.configurations.mainConfig.file_name }}: |-
    global:
      resolve_timeout: {{ .Values.alertManager.configurations.mainConfig.resolve_timeout }}

    route:
      group_by: ['alertname']
      group_wait: {{ .Values.alertManager.configurations.mainConfig.group_wait }}
      group_interval: {{ .Values.alertManager.configurations.mainConfig.group_interval }}
      repeat_interval: {{ .Values.alertManager.configurations.mainConfig.repeat_interval }}
      receiver: 'email'
    receivers:
    - name: 'email'
      email_configs:
      {{- with .Values.alertManager.emailInfo }}
      - to: {{ .to }}
        from: {{ .from }}
        smarthost: {{ .smtpServer }}
        auth_username: {{ .authUsername }}
        auth_identity: {{ .authIdentity }}
        auth_password: {{ .authPassword }}
      {{- end }}
  
  {{ .Values.alertManager.configurations.webConfig.file_name }}: |-
    {{- with .Values.alertManager.configurations.webConfig.authentication }}
    {{- if .enabled }}
    basic_auth_users:
      {{ htpasswd .username .password | replace ":" ": "}}
    {{- end }}
    {{ end }}
