apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitoring.alertManager.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    {{- include "monitoring.alertManager.selectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "monitoring.alertManager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.alertManager.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- include "monitoring.alertManager.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.alertManager.containerName }}
        image: {{ .Values.alertManager.image.repository }}:{{ .Values.alertManager.image.tag }}
        args:
        {{- range .Values.alertManager.runArgs }}
          - {{ tpl . $ }}
        {{- end}}
        ports:
        - containerPort: 9093
        {{- with .Values.alertManager.resources }}
        resources:
          limits:
            cpu: {{ .limits.cpu }}
            memory: {{ .limits.memory }}
          requests:
            cpu: {{ .requests.cpu }}
            memory: {{ .requests.memory }}
        {{- end }}
        volumeMounts:
          - name: configs
            mountPath: {{ .Values.alertManager.configurations.config_dir }}
      volumes:
        - name: configs
          configMap:
            defaultMode: 420
            name: {{ include "monitoring.alertManager.cmname" . }}