apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.alertManager.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- include "monitoring.alertManager.selectorLabels" . | nindent 4}}
  ports:
    - protocol: TCP
      port: {{ .Values.alertManager.service.port }}
      targetPort: 9093