apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "database.fullname" .) }}
  namespace: {{ include "database.namespace" . | quote }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "database.selectorLabels" . | nindent 4 }}
