apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    {{- include "monitoring.nodeExporter.selectorLabels" . | nindent 4 }}
    {{- include "monitoring.labels" . | nindent 4 }}
  name: {{ include "monitoring.nodeExporter.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      {{- include "monitoring.nodeExporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.nodeExporter.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "monitoring.nodeExporter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        {{- range .Values.nodeExporter.runArgs }}
        - {{ . }}
        {{- end }}
        {{- with .Values.nodeExporter.mountPaths }}
        {{- if .sys.enabled }}
        - --path.sysfs={{ .sys.path }}
        {{- end }}
        {{- if .root.enabled}}
        - --path.rootfs={{ .root.path }}
        {{- end }}
        {{- end}}
        name: {{ .Values.nodeExporter.containerName }}
        image: prom/node-exporter
        ports:
          - containerPort: 9100
            protocol: TCP
        {{- with .Values.nodeExporter.resources }}
        resources:
          limits:
            cpu: {{ .limits.cpu }}
            memory: {{ .limits.memory }}
          requests:
            cpu: {{ .requests.cpu }}
            memory: {{ .requests.memory }}
        {{- end }}
        volumeMounts:
        {{- with .Values.nodeExporter.mountPaths }}
        {{- if .sys.enabled }}
        - mountPath: {{ .sys.path }}
          mountPropagation: HostToContainer
          name: sys
        {{- end }}
        {{- if .root.enabled }}
        - mountPath: {{ .root.path }}
          mountPropagation: HostToContainer
          name: root
        {{- end }}
        {{- end }}
      volumes:
      {{- with .Values.nodeExporter.mountPaths }}
      {{- if .sys.enabled }}
      - hostPath:
          path: {{ .sys.hostPath }}
        name: sys
      {{- end }}
      {{- if .root.enabled }}
      - hostPath:
          path: {{ .root.hostPath }}
        name: root
      {{- end }}
      {{- end }}
