apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-digi
  namespace: ci-cd
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: najafi.shayan4237@gmail.com
    privateKeySecretRef:
      name: account-key-digi
    solvers:
    - http01:
       ingress:
         class: nginx
