{
 "title": "api server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "total response size",
   "type": "timeseries",
   "description": "sum of average response size from api server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_response_sizes_sum{job=\"kubernetes-apiservers\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kube api server error rate",
   "type": "timeseries",
   "description": "number of responses with status code 4xx or 5xx from kube API server",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"kubernetes-apiservers\",code=~\"[45]..\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate of api server latency",
   "type": "stat",
   "description": "total rate of api server latency in last 5 minuets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_count{job=\"kubernetes-apiservers\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate of etcd latency",
   "type": "stat",
   "description": "total rate of etcd latency in last 5 minuets",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(etcd_request_duration_seconds_count{job=\"kubernetes-apiservers\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}