{
 "title": "application",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "status_code",
    "query": {
     "query": "label_values(http_requests_total, status)"
    }
   },
   {
    "name": "handler",
    "query": {
     "query": "label_values(http_response_size_bytes_sum, handler)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(http_request_duration_seconds_count, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "average request latency",
   "type": "timeseries",
   "description": "average request latency in the last 2 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{handler=~\"$handler\", instance=~\"$instance\"}[2m])",
     "legendFormat": "average latency for {{instance}} - {{handler}}"
    }
   ]
  },
  {
   "title": "request and response size",
   "type": "timeseries",
   "description": "this chart shows the average request and response size per second in the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(http_request_size_bytes_sum{handler=~\"$handler\"}[5m]))",
     "legendFormat": "request size rate"
    },
    {
     "expr": "avg(rate(http_response_size_bytes_sum{handler=~\"$handler\"}[5m]))",
     "legendFormat": "response size rate"
    }
   ]
  },
  {
   "title": "response status codes",
   "type": "timeseries",
   "description": "this chart demonstrates on average in last 5 minuets, how many requests was resolved with different status codes per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=\"$status_code\"}[5m]))",
     "legendFormat": "total unsuccessful request rate"
    }
   ]
  }
 ]
}