{
 "title": "resources",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=\"node-exporter\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "disk usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_filesystem_avail_bytes{device=~\"/dev.*\", instance=~\"$instance\"} / node_filesystem_size_bytes{device=~\"/dev.*\", instance=~\"$instance\"})) ",
     "legendFormat": "{{device}} - {{mountpoint}}"
    },
    {}
   ]
  },
  {
   "title": "memory usage",
   "type": "gauge",
   "description": "memory usage percentage",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - node_memory_MemAvailable_bytes{instance=~\"$instance\"} / on(instance) node_memory_MemTotal_bytes{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "received traffic rate ",
   "type": "timeseries",
   "description": "rate of incoming traffic at the last minute. In other words, it is the speed of incoming traffic in the last minuet. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$instance\", device=~\"en.+|wl.+|eth.+\"}[1m]) / 1024 / 1024",
     "legendFormat": "{{device}}"
    },
    {}
   ]
  },
  {
   "title": "CPU load per node",
   "type": "gauge",
   "description": "average CPU load on each node",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * node_load5{instance=~\"$instance\"} / on (instance) count(node_cpu_seconds_total{instance=~\"$instance\", job=\"node-exporter\", mode=\"system\"}) by(instance) ",
     "legendFormat": "{{$instance}}"
    }
   ]
  }
 ]
}