apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.grafana.cmname" . }}
  namespace: {{ .Release.Namespace }}
data:
  ds.yaml: |-
    apiVersion: 1
    datasources:
    - name: {{ .Values.grafana.configurations.datasources.name }}
      type: {{ .Values.grafana.configurations.datasources.type }}
      access: {{ .Values.grafana.configurations.datasources.access }}

      {{- $url := .Values.prometheus.service.name -}}
      {{- $port := .Values.prometheus.service.port -}}


      {{- with .Values.prometheus.configurations.webConfig.authentication }}
      {{- if .enabled }}
      url: http://{{ .username }}:{{ .password }}@{{ $url }}:{{ $port }}
      {{- else }}
      url: http://{{ $url }}:{{ $port }}
      {{- end }}
      {{- end }}