apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "monitoring.grafana.selectorLabels" . | nindent 4 }}
    {{- include "monitoring.labels" . | nindent 4 }}
  name: {{ include "monitoring.grafana.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "monitoring.grafana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
          {{- with .Values.grafana.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "monitoring.grafana.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.grafana.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.grafana.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Values.grafana.containerName }}
        securityContext:
          {{- toYaml .Values.grafana.securityContext | nindent 10 }}
        image: {{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}
        imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
        args:
        {{- range .Values.grafana.runArgs }}
          - {{ tpl . $ }}
        {{- end}}
        ports:
        - containerPort: {{ .Values.grafana.image.port }}
        {{- with .Values.grafana.resources }}
        resources:
          limits:
            cpu: {{ .limits.cpu }}
            memory: {{ .limits.memory }}
          requests:
            cpu: {{ .requests.cpu }}
            memory: {{ .requests.memory }}
        {{- end }}
        env:
          {{- range $key, $val := .Values.grafana.envVars }}
          - name: {{ $key }}
            value: {{ $val }}
          {{- end }}
          {{- if .Values.grafana.createAdminUser.enabled }}
          - name: GF_SECURITY_ADMIN_USER
            value: {{ .Values.grafana.createAdminUser.user }}
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: {{ .Values.grafana.createAdminUser.password }}
          {{- end }}
        
      {{- with .Values.grafana.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grafana.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grafana.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
