apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- include "monitoring.grafana.selectorLabels" . | nindent 4}}
  ports:
    - protocol: TCP
      port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.image.port }}