apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "database.fullname" .) }}
  namespace: {{ include "database.namespace" . | quote }}
  labels:
  {{- include "database.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: galera
      port: 4567
      targetPort: galera
    - name: ist
      port: 4568
      targetPort: ist
    - name: sst
      port: 4444
      targetPort: sst
  publishNotReadyAddresses: {{ .Values.service.headless.publishNotReadyAddresses }}
  selector: {{- include "database.selectorLabels" . | nindent 4 }}