{{- if (include "database.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "database.fullname" .) }}
  namespace: {{ include "database.namespace" . | quote }}
  labels: 
  {{- include "database.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ default (randAlphaNum 10) .Values.rootUser.password | b64enc | quote }}
  mariadb-password: {{ default (randAlphaNum 10) .Values.db.password | b64enc | quote }}
{{- end }}