apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "digiapp.name" . }}
  labels:
    {{- include "digiapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "digiapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "digiapp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /docs
              port: http
          readinessProbe:
            httpGet:
              path: /docs
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CONFIG_ADDR
              value: {{ .Values.secretConfig.workingDir }}/{{ .Values.secretConfig.configFilePath }}/{{ .Values.secretConfig.config_file_name }}
          {{- range $key, $val := .Values.image.environments }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- if .Values.secretConfig.enabled }}
          volumeMounts:
            - name: vol-secret
              mountPath: {{ .Values.secretConfig.workingDir }}/{{ .Values.secretConfig.configFilePath }}
          {{- end }}
      {{- if .Values.secretConfig.enabled }}
      volumes:
        - name: vol-secret
          secret:
            secretName: {{ include "digiapp.secretName" . }}
      {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
