{{- if .Values.secretConfig.enabled -}}
apiVersion: {{ template "digiapp.apiVersion" . }}
data:
  {{ .Values.secretConfig.config_file_name }}: {{ .Values.secretConfig.data | toJson | b64enc }}

kind: Secret
metadata:
  name: {{ .Values.secretConfig.secret_name | default "digiapp-secret" }}-{{ .Release.Name }}
type: {{ .Values.secretConfig.secret_type }}

{{- end }}