{{- if .Values.secretConfig.enabled -}}
apiVersion: v1
data:
  {{ .Values.secretConfig.config_file_name }}: {{ .Values.secretConfig.data | toJson | b64enc }}

kind: Secret
metadata:
  name: {{ include "digiapp.secretName" . }}
type: Opaque

{{- end }}