pipeline {
    agent any
    environment {
        commit = "{env.GIT_PREVIOUS_COMMIT}"
        registry = "shayannjf/digiapp"
        registryCredential = 'dockerhub_credential'
        repositoryCredential = 'digikala_repository_token'
        repositoryUrl = 'https://github.com/njfiSHAYAN/digikala.git'
        branchName = 'jenkins'
    }
    stages {
        // connect to git
        stage('Cloning Git') {
            steps {
                checkout([$class: 'GitSCM',
                          branches: [[name: branchName]],
                          doGenerateSubmoduleConfigurations: false,
                          extensions: [],
                          submoduleCfg: [],
                          userRemoteConfigs: [[credentialsId: repositoryCredential, url: repositoryUrl]]])
            }
        }
        
        stage ('test commit') {
            steps {
                script {
                    
                    echo env.GIT_PREVIOUS_COMMIT
                }
            }
        }
    
        // Building Docker images
        // stage('Building imagee') {
        //    steps {
        //        sh "img build -t ${registry}:${BUILD_TAG} ./application"
        //    }
        // }

        // // Pushing image
        // stage('Pushing image') {
        //    steps {
        //        withCredentials([usernamePassword(credentialsId: registryCredential, usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
        //           sh 'img login --username $USERNAME --password $PASSWORD'
        //         }
        //           sh "img push ${registry}:${BUILD_TAG}"
        //    }
        // }
}
}
