- name: add helm key and repository
  become: true  
  block:
    - name: 'add helm key'
      ansible.builtin.apt_key:
        url: "https://baltocdn.com/helm/signing.asc"
        state: present

    - name: install apt-transport-https 
      ansible.builtin.apt:
        update_cache: yes
        name: apt-transport-https 
        state: present

    - name: 'add helm repository'
      ansible.builtin.apt_repository:
        repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
        state: present
        
- name: install helm
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    name: helm
    state: present