---
- name: gather package info to see if helm is installed
  package_facts:
    manager: apt

- name: install helm
  include_tasks: "install-helm.yaml"
  when: "'helm' not in ansible_facts.packages"

- name: copy chart to host
  copy:
    src: "{{ chart_src }}/{{ chart_name }}"
    dest: "{{ chart_dest }}"
    owner: "{{ chart_owner }}"
    group: "{{ chart_group }}"
    mode: " {{ chart_mode }}"
  when: "onlyHelm | bool == False"

- name: copy values file
  template:
    src: "{{ values_src }}"
    dest: "{{ values_dest }}/{{ values_file_name }}"
    owner: "{{ values_owner }}"
    group: "{{ values_group }}"
    mode: " {{ values_mode }}"
  when: "values_enabled is true and onlyHelm | bool == False"

- name: install charts with values file. skip if not available
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ release_name }}"
    chart_ref: "{{ chart_dest }}/{{ chart_name }}"
    release_namespace: "{{ release_namespace }}"
    create_namespace: yes
    values_files:
      - "{{ values_dest }}/{{ values_file_name }}"
    values: "{{ values }}"
    wait: "{{ wait }}"
  when: "values_enabled is true and onlyHelm | bool == False"

- name: install charts without values file. helm is already installed if values file is provided
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ release_name }}"
    chart_ref: "{{ chart_dest }}/{{ chart_name }}"
    release_namespace: "{{ release_namespace }}"
    create_namespace: yes
    values: "{{ values }}"
    wait: "{{ wait }}"
  when: "values_enabled is false and onlyHelm | bool == False"
