---
- name: install helm
  include_tasks: "install-helm.yaml"

- name: copy chart to host
  copy:
    src: "{{ chart_src }}/{{ chart_name }}"
    dest: "{{ chart_dest }}"
    owner: "{{ chart_owner }}"
    group: "{{ chart_group }}"
    mode: " {{ chart_mode }}"

- name: copy values file
  copy:
    src: "{{ values_src }}"
    dest: "{{ values_dest }}/{{ values_file_name }}"
    owner: "{{ values_owner }}"
    group: "{{ values_group }}"
    mode: " {{ values_mode }}"
  when: "values_enabled is true"

- name: install charts with values file. skip if not available
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ release_name }}"
    chart_ref: "{{ chart_dest }}/{{ chart_name }}"
    release_namespace: "{{ release_namespace }}"
    create_namespace: yes
    atomic: yes
    values_files:
      - "{{ values_dest }}/{{ values_file_name }}"
  when: "values_enabled is true"

- name: install charts without values file. helm is already installed if values file is provided
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ release_name }}"
    chart_ref: "{{ chart_dest }}/{{ chart_name }}"
    release_namespace: "{{ release_namespace }}"
    create_namespace: yes
    atomic: yes
  when: "values_enabled is false"
