apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.blackbox.cmname" . }}
  namespace: {{ .Values.namespace }}
data:
  {{ .Values.blackbox.configurations.mainConfig.file_name }}: |-
    {{- tpl .Values.blackbox.configurations.mainConfig.data . | nindent 4 }}
  
