apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.blackbox.cmname" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.blackbox.configurations.mainConfig.file_name }}: |-
    modules:
      http_2xx:
        prober: http
        http:
          preferred_ip_protocol: "ip4"

  
