- name: create cluster
  import_playbook: "install-kubeadm/playbook.yaml"

- name: install monitoring
  import_playbook: "playbooks/infrastructure/monitoring/playbook.yaml"
  vars:
    chart_name: monitoring
    chart_src: "../helmCharts"
    chart_dest: "/tmp/charts"
    chart_owner: "{{ ansible_user_id }}"
    chart_group: "{{ ansible_user_id }}"
    chart_mode: 0644

    values_enabled: false
    values_src: "values.yaml"
    values_dest: "/tmp/charts"
    values_owner: "{{ ansible_user_id }}"
    values_group: "{{ ansible_user_id }}"
    values_mode: 0644

    release_name: "test"
    release_namespace: "default"

    kubeconfig: ~/admin.conf