- name: Install and Config DB + redis
  hosts: "{{ (groups['masters'] | shuffle)[0] }}"
  vars:
    src: "../../../../helmCharts"
  roles:
    - role: "apply-helmChart"
      vars: 
        chart_name: "database"
        release_name: "galera"
        release_namespace: "default"
        chart_src: "{{ src }}"
        values:
            db:
              user: "{{ db_user }}"
              password: "{{ db_pass }}"
              name: "{{ db_name }}"
            service:
                port: "{{ db_port }}"

    - role: "apply-helmChart"
      vars: 
        chart_name: "redis-sentinel"
        release_name: "cache"
        release_namespace: "default"
        chart_src: "{{ src }}"
