apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configuration" (include "redis-sentinel.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "redis-sentinel.labels" . | nindent 4 }}
data:
  redis.conf: |-
    bind 0.0.0.0
    # configurations for snaposhot and AOF
    # read more : https://redis.io/docs/manual/persistence/
    dbfilename dump.rdb
    dir %data-dir%
    appendonly yes
    appendfilename "appendonly.aof"
    # port, each redis nodes will be used
    port %port-number%
    {{ .Values.redis.config | nindent 4 }}
    
  {{- if .Values.sentinel.enabled }}
  sentinel.conf: |-
    dir "/data"
    port {{ .Values.sentinel.containerPorts.sentinel }}
    sentinel resolve-hostnames yes
    sentinel monitor {{ .Values.sentinel.masterSet }} {{ template "redis-sentinel.fullname" . }}-node-0.{{ template "redis-sentinel.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }} {{ .Values.service.ports.redis }} {{ .Values.sentinel.quorum }}
    sentinel down-after-milliseconds {{ .Values.sentinel.masterSet }} {{ .Values.sentinel.downAfterMilliseconds }}
    sentinel failover-timeout {{ .Values.sentinel.masterSet }} {{ .Values.sentinel.failoverTimeout }}
    sentinel parallel-syncs {{ .Values.sentinel.masterSet }} {{ .Values.sentinel.parallelSyncs }}
    {{- if and .Values.auth.enabled .Values.auth.password }}
    sentinel auth-pass {{ .Values.sentinel.masterSet }} {{ .Values.auth.sentinel.password }}
    sentinel auth-user {{ .Values.sentinel.masterSet }} {{ .Values.auth.sentinel.user }}
    {{- end }}
    {{ .Values.sentinel.config | nindent 4 }}
  {{- end }}

---
{{- if .Values.auth.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-acl" (include "redis-sentinel.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "redis-sentinel.labels" . | nindent 4 }}
data:
  acl.conf: |-
    {{ .Values.auth.acl.config | nindent 4 }}
{{- end }}
