apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-health" (include "redis-sentinel.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "redis-sentinel.labels" . | nindent 4 }}
data:
  ping_readiness_local.sh: |-
    #!/bin/bash
    {{- if and .Values.auth.enabled }}
    export REDISCLI_AUTH="{{ .Values.auth.password }}"
    {{- end }}
    response=$(
      timeout -s 3 $1 \
      redis-cli \
        {{- if .Values.auth.enabled }}
        --user {{ .Values.auth.authUser }} \
        {{- end }}
        -h localhost \
        -p {{ .Values.redis.containerPorts.redis }} \
        ping
    )
    if [ "$?" -eq "124" ]; then
      echo "Timed out"
      exit 1
    fi
    if [ "$response" != "PONG" ]; then
      echo "$response"
      exit 1
    fi
  ping_liveness_local.sh: |-
    #!/bin/bash
    {{- if and .Values.auth.enabled  }}
    export REDISCLI_AUTH="{{ .Values.auth.password }}"
    {{- end }}
    response=$(
      timeout -s 3 $1 \
      redis-cli \
        {{- if .Values.auth.enabled }}
        --user {{ .Values.auth.authUser }} \
        {{- end }}
        -h localhost \
        -p {{ .Values.redis.containerPorts.redis }} \
        ping
    )
    if [ "$?" -eq "124" ]; then
      echo "Timed out"
      exit 1
    fi
    responseFirstWord=$(echo $response | head -n1 | awk '{print $1;}')
    if [ "$response" != "PONG" ] && [ "$responseFirstWord" != "LOADING" ] && [ "$responseFirstWord" != "MASTERDOWN" ]; then
      echo "$response"
      exit 1
    fi
{{- if .Values.sentinel.enabled }}
  ping_sentinel.sh: |-
    #!/bin/bash
    
    # [[ -n "$REDIS_PASSWORD" ]] && export REDISCLI_AUTH="$REDIS_PASSWORD"

    response=$(
      timeout -s 3 $1 \
      redis-cli \
        -h localhost \
        -p {{ .Values.sentinel.containerPorts.sentinel }} \
        ping
    )
    if [ "$?" -eq "124" ]; then
      echo "Timed out"
      exit 1
    fi
    if [ "$response" != "PONG" ]; then
      echo "$response"
      exit 1
    fi
{{- end }}
