{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "redis-sentinel.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "redis-sentinel.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.auth.replication.password | b64enc | quote }}
  sentinel-password: {{ .Values.auth.sentinel.password | b64enc | quote }}
{{- end -}}