apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "redis-sentinel.fullname" .) }}
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  
  ports:
    - name: redis
      port: {{ .Values.service.ports.redis }}
      targetPort: {{ .Values.redis.containerPorts.redis }}
    

  selector:
    {{- include "redis-sentinel.selectorLabels" . | nindent 4 }}
--- 

apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "redis-sentinel.fullname" .) }}
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  publishNotReadyAddresses: true
  ports:
    - name: redis
      port: {{ .Values.service.ports.redis }}
      targetPort: {{ .Values.redis.containerPorts.redis }}
    {{- if .Values.sentinel.enabled }}
    - name: sentinel
      port: {{ .Values.service.ports.sentinel }}
      targetPort: {{ .Values.sentinel.containerPorts.sentinel }}
    {{- end }}
  selector:
    {{- include "redis-sentinel.selectorLabels" . | nindent 4 }}
