apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "monitoring.prometheus.clusterRoleNmae" . }}-binding
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "monitoring.prometheus.clusterRoleNmae" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "monitoring.prometheus.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}

