apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.prometheus.cmname" . }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
  {{ .Values.prometheus.configurations.rules.file_name }}: |-
    {{ tpl .Values.prometheus.configurations.rules.data . | nindent 4 }}
  {{ .Values.prometheus.configurations.mainConfig.file_name }}: |-
    {{ tpl .Values.prometheus.configurations.mainConfig.data . | nindent 4 }}
  {{ .Values.prometheus.configurations.webConfig.file_name }}: |-
    {{ tpl .Values.prometheus.configurations.webConfig.data . | nindent 4 }}
