apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.service.name }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.image.port }}
      protocol: TCP
  selector:
    {{- include "monitoring.prometheus.selectorLabels" . | nindent 4 }}
