apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.service.name }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: 9090
      protocol: TCP
  selector:
    {{- include "monitoring.prometheus.selectorLabels" . | nindent 4 }}
