groups:
- name: Instances
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 2m
    labels:
      severity: crititcal
      domain: instances
    annotations:
      description: '{{ `{{ $labels.instance }}` }} of job {{ `{{ $labels.job }}` }} has been down for more than 2 minutes.'
      summary: 'Instance {{ `{{ $labels.instance }}` }} down'
- name: BlackboxProbe
  rules:
  - alert: AppDown
    expr: probe_success == 0
    for: 2m
    labels:
      severity: critical
      domain: application
    annotations:
      description:  '{{ `{{ $labels.instance }}` }} of job {{ `{{ $labels.job }}` }} has been down for more than 2 minutes.'
      summary: 'Application {{ `{{ $labels.instance }}` }} down'